// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SQLiteAspNetCoreMvcIdentity.Data;
using System;

namespace SQLiteAspNetCoreMvcIdentity.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180423202319_VragenAntwoorden")]
    partial class VragenAntwoorden
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SQLiteAspNetCoreMvcIdentity.Models.Antwoord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Afbeelding");

                    b.Property<bool>("Afgesloten");

                    b.Property<string>("EigenaarId");

                    b.Property<DateTime>("LaatsteWijziging");

                    b.Property<string>("Tekst");

                    b.Property<int?>("VraagId");

                    b.HasKey("Id");

                    b.HasIndex("EigenaarId");

                    b.HasIndex("VraagId");

                    b.ToTable("Antwoord");
                });

            modelBuilder.Entity("SQLiteAspNetCoreMvcIdentity.Models.AntwoordCommentaar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Commentaar");

                    b.Property<string>("EigenaarId");

                    b.Property<DateTime>("LaatsteWijziging");

                    b.HasKey("Id");

                    b.HasIndex("EigenaarId");

                    b.ToTable("AntwoordCommentaar");
                });

            modelBuilder.Entity("SQLiteAspNetCoreMvcIdentity.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("SQLiteAspNetCoreMvcIdentity.Models.Vraag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Afbeelding");

                    b.Property<DateTime>("LaatsteWijziging");

                    b.Property<double>("MaxPunten");

                    b.Property<string>("Opmerkingen");

                    b.Property<string>("Tekst");

                    b.Property<int?>("VragenlijstId");

                    b.HasKey("Id");

                    b.HasIndex("VragenlijstId");

                    b.ToTable("Vraag");
                });

            modelBuilder.Entity("SQLiteAspNetCoreMvcIdentity.Models.Vragenlijst", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EigenaarId");

                    b.Property<bool>("Gequoteerd");

                    b.Property<DateTime>("LaatsteWijziging");

                    b.Property<string>("Omschrijving");

                    b.Property<string>("Opmerkingen");

                    b.Property<string>("Titel");

                    b.HasKey("Id");

                    b.HasIndex("EigenaarId");

                    b.ToTable("Vragenlijst");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SQLiteAspNetCoreMvcIdentity.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SQLiteAspNetCoreMvcIdentity.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SQLiteAspNetCoreMvcIdentity.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SQLiteAspNetCoreMvcIdentity.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SQLiteAspNetCoreMvcIdentity.Models.Antwoord", b =>
                {
                    b.HasOne("SQLiteAspNetCoreMvcIdentity.Models.ApplicationUser", "Eigenaar")
                        .WithMany()
                        .HasForeignKey("EigenaarId");

                    b.HasOne("SQLiteAspNetCoreMvcIdentity.Models.Vraag", "Vraag")
                        .WithMany("Antwoorden")
                        .HasForeignKey("VraagId");
                });

            modelBuilder.Entity("SQLiteAspNetCoreMvcIdentity.Models.AntwoordCommentaar", b =>
                {
                    b.HasOne("SQLiteAspNetCoreMvcIdentity.Models.ApplicationUser", "Eigenaar")
                        .WithMany()
                        .HasForeignKey("EigenaarId");
                });

            modelBuilder.Entity("SQLiteAspNetCoreMvcIdentity.Models.Vraag", b =>
                {
                    b.HasOne("SQLiteAspNetCoreMvcIdentity.Models.Vragenlijst")
                        .WithMany("Vragen")
                        .HasForeignKey("VragenlijstId");
                });

            modelBuilder.Entity("SQLiteAspNetCoreMvcIdentity.Models.Vragenlijst", b =>
                {
                    b.HasOne("SQLiteAspNetCoreMvcIdentity.Models.ApplicationUser", "Eigenaar")
                        .WithMany()
                        .HasForeignKey("EigenaarId");
                });
#pragma warning restore 612, 618
        }
    }
}
